HCalibration::usage="HCalibration[] records actual synthetic design diagnostics, not industry benchmarks.";
HCalibration[]:=Module[{s,gate,f,em,r,bands,out},
 s=First[HQuery["SELECT sum(n) sessions,count(*) active_user_days,avg(n)::float8 sessions_per_active_day,avg((n>1)::int)::float8 multi_session_day_fraction FROM (SELECT user_id,session_date,count(*) n FROM horizon.sessions GROUP BY 1,2) d"]];
 Do[$HM["session_diagnostics/"<>k]=s[k],{k,Keys[s]}];
 f=Select[HReadTable["funnel.csv"],#["dimension"]=="overall"&&#["name"]=="chapter_3"&];gate=First[Select[HReadTable["progression_diagnosis.csv"],#["level"]==12&]];
 em=Import[HPath["outputs","models","wolfram_evaluation.json"],"RawJSON"];
 r=Join[<|"users"->$HM["users"]|>,s,<|"d1_retention"->$HM["retention/d1"],"d7_retention"->$HM["retention/d7"],"d30_retention"->$HM["retention/d30"],"payer_conversion"->$HM["payer_conversion"],"arpu"->$HM["arpu"],"arppu"->$HM["arppu"],"chapter2_to_chapter3_conversion"->First[f]["conversion"],"level12_boss_failure_rate"->gate["failure_rate"],"android_d7_retention"->$HM["retention/device/Android/d7"],"pc_d7_retention"->$HM["retention/device/PC/d7"],"ios_d7_retention"->$HM["retention/device/iOS/d7"],"device_max_gap"->(Max[Table[$HM["retention/device/"<>d<>"/d7"],{d,{"Android","PC","iOS"}}]]-Min[Table[$HM["retention/device/"<>d<>"/d7"],{d,{"Android","PC","iOS"}}]]),"reactivation_eligible"->$HM["reactivation/eligible"],"reactivation_rate"->$HM["return_rate"],"logistic_auc"->em["logistic"]["roc_auc"],"nonlinear_auc"->em["nonlinear"]["roc_auc"],"lift_at_10pct"->em["logistic"]["lift_at_10pct"]|>];
 bands=<|"sessions_per_active_day"->{1.2,1.6},"d1_retention"->{.3,.5},"d7_retention"->{.12,.3},"d30_retention"->{.05,.18},"payer_conversion"->{.02,.10},"chapter2_to_chapter3_conversion"->{.55,.75},"level12_boss_failure_rate"->{.55,.80},"device_max_gap"->{.02,.08}|>;
 out=KeyValueMap[Function[{k,v},With[{b=Lookup[bands,k,{Null,Null}]},<|"metric"->k,"value"->N[v],"target_band_low"->b[[1]],"target_band_high"->b[[2]],"status"->If[KeyExistsQ[bands,k],If[b[[1]]<=v<=b[[2]],"WITHIN_DESIGN_BAND","REVIEW_SOFT_BAND"],"OBSERVED"],"band_type"->"synthetic design guardrail; not industry benchmark"|>]],r];
 If[!DirectoryQ[HPath["outputs","validation"]],CreateDirectory[HPath["outputs","validation"]]];
 HCSV[HPath["outputs","validation","synthetic_calibration.csv"],out];HJSON[HPath["outputs","validation","synthetic_calibration.json"],<|"values"->r,"diagnostics"->out,"guardrail_note"->"Soft synthetic design guardrails, not industry benchmarks or seed optimization targets."|>];r];
