HExperiments::usage="HExperiments[] computes two-proportion power plans from actual baselines.";
HPowerN[p_,d_]:=Ceiling[2 (Quantile[NormalDistribution[],.975]+Quantile[NormalDistribution[],.8])^2/(2 ArcSin[Sqrt[p]]-2 ArcSin[Sqrt[Min[.999,p+d]]])^2];
(* Same balanced, two-sided noncentral-t power calculation as TTestIndPower. *)
HPowerMean[sd_]:=Module[{power,n,e=.3/sd},power[n_?NumericQ]:=With[{df=2 n-2,delta=e Sqrt[n/2]},With[{crit=Quantile[StudentTDistribution[df],.975]},1-CDF[NoncentralStudentTDistribution[df,delta],crit]+CDF[NoncentralStudentTDistribution[df,delta],-crit]]];Ceiling[n/.FindRoot[power[n]==.8,{n,2 (Quantile[NormalDistribution[],.975]+Quantile[NormalDistribution[],.8])^2/e^2,2,1000000}]]];
HExperiments[]:=Module[{f,a,pred,y,baseb,r,sd,plans,basec,nc,eligiblec},
 f=HSQLFile["09_gate_experiment.sql"];HCSV[HPath["outputs","tables","gate_eligibility.csv"],f];a=Mean[Lookup[f,"completed_within3"]];
 pred=Rest[Import[HPath["outputs","models","wolfram_predictions.csv"],"CSV"]];y=Take[Reverse[SortBy[pred,#[[3]]&]],Ceiling[Length[pred]/10]][[All,1]];
 baseb=N[First[HQuery["SELECT count(DISTINCT s.user_id) n FROM horizon.sessions s JOIN horizon.users u USING(user_id) WHERE s.session_date=u.register_date+30 AND s.user_id IN("<>StringRiffle[ToString/@Round[y],","]<>")"]]["n"]/Length[y]];
 r=<|"A"-><|"baseline"->N[a],"eligible_n"->Length[f],"completed_n"->Total[Lookup[f,"completed_within3"]],"gate_level"->12,"gate_failure_rate_d0_7"->First[Select[HReadTable["progression_diagnosis.csv"],#["level"]==12&]]["failure_rate"],"absolute_mde"->.025,"per_arm"->HPowerN[a,.025],"population"->"First Level 12 boss attempt; user 1:1 randomization at exposure","primary"->"Chapter 3 completion within 3 days of first Level 12 attempt"|>,"B"-><|"baseline"->N[baseb],"absolute_mde"->.03,"per_arm"->HPowerN[baseb,.03],"population"->"Top decile ranked at D7","primary"->"Exact-day D30 retention"|>,"C"-><|"assignment"->"returning user randomized at return; complete D0-D6 followup","primary"->"post-return active days","mde_days"->.3|>,"alpha"->.05,"power"->.8,"status"->"Planning assumptions, no experiment executed"|>;
 sd=First[HQuery["WITH eligible AS(SELECT u.user_id FROM horizon.users u WHERE u.register_date<DATE '2026-04-17' AND NOT EXISTS(SELECT 1 FROM horizon.sessions s WHERE s.user_id=u.user_id AND s.session_date BETWEEN DATE '2026-04-17' AND DATE '2026-04-30')), r AS(SELECT e.user_id,min(session_date) rd FROM eligible e JOIN horizon.sessions s USING(user_id) WHERE session_date BETWEEN DATE '2026-05-01' AND DATE '2026-05-07' GROUP BY e.user_id), p AS(SELECT r.user_id,count(DISTINCT session_date) n FROM r JOIN horizon.sessions s ON s.user_id=r.user_id AND s.session_date BETWEEN rd AND rd+6 GROUP BY r.user_id) SELECT stddev_samp(n)::float8 sd FROM p"]]["sd"];
 basec=$HM["reactivation/post_return_days7"];eligiblec=$HM["reactivation/returned"];nc=HPowerMean[sd];
 r["C"]=Join[r["C"],<|"baseline"->basec,"eligible_n"->eligiblec,"per_arm"->nc,"observed_sd"->sd|>];
 plans={<|"experiment"->"A","population"->r["A"]["population"],"primary"->r["A"]["primary"],"eligible_n"->Length[f],"completed_n"->Total[Lookup[f,"completed_within3"]],"baseline"->N[a],"mde"->.025,"per_arm"->r["A"]["per_arm"],"treatment"->"关卡难度、资源或引导优化","guardrails"->"Mature D7/D14 retention, crashes, playtime, spend, downstream progression"|>,
 <|"experiment"->"B","population"->"Top decile risk ranked at D7","primary"->r["B"]["primary"],"eligible_n"->Length[y],"completed_n"->Null,"baseline"->baseb,"mde"->.03,"per_arm"->r["B"]["per_arm"],"treatment"->"个性化任务提示与资源扶持","guardrails"->"Crashes, spend, opt-out; D22-D30 activity secondary"|>,
 <|"experiment"->"C","population"->"14-day silent users randomized at observed return","primary"->"Post-return D0-D6 active days","eligible_n"->eligiblec,"completed_n"->Null,"baseline"->basec,"mde"->.3,"per_arm"->nc,"treatment"->"个性化回流内容导航","guardrails"->"Crashes, disengagement, spend"|>};
 HCSV[HPath["outputs","tables","experiment_design.csv"],plans];HJSON[HPath["outputs","metrics","power_analysis.json"],<|"alpha"->.05,"power"->.8,"two_sided"->True,"experiments"->plans,"implementation"->"Native Wolfram; balanced noncentral Student t for C"|>];
 HJSON[HPath["outputs","metrics","experiments_wolfram.json"],r];r];
