HRetention::usage="HRetention[] computes mature exact-day retention and stratified rates.";
HWilson[k_,n_]:=Module[{p=N[k/n],z=1.959963984540054,c,h},c=(p+z^2/(2 n))/(1+z^2/n);h=z Sqrt[p(1-p)/n+z^2/(4 n^2)]/(1+z^2/n);{c-h,c+h}];
HRetention[]:=Module[{curve,groups,weekly,q,ci},curve=HSQLFile["03_retention.sql"];curve=Map[Function[r,ci=HWilson[r["retained"],r["eligible"]];Join[r,<|"ci_low"->ci[[1]],"ci_high"->ci[[2]]|>]],curve];
 HCSV[HPath["outputs","tables","retention_curve.csv"],curve];Do[$HM["retention/d"<>ToString[r["d"]]]=r["rate"];$HM["retention/eligible/d"<>ToString[r["d"]]]=r["eligible"],{r,curve}];
 q="WITH a AS (SELECT DISTINCT user_id,session_date FROM horizon.sessions),h AS(SELECT unnest(ARRAY[1,7,30]) d), x AS(SELECT u.*,h.d,(a.user_id IS NOT NULL)::int retained FROM horizon.users u CROSS JOIN h LEFT JOIN a ON a.user_id=u.user_id AND a.session_date=u.register_date+h.d WHERE u.register_date+h.d<=DATE '2026-06-29') ";
 groups=HQuery[q<>StringRiffle[Map[Function[pair,"SELECT '"<>pair[[1]]<>"' dimension,"<>pair[[2]]<>" category,d,count(*) eligible,sum(retained) retained,avg(retained)::float8 rate FROM x GROUP BY "<>pair[[2]]<>",d"],{{"market","market"},{"channel","acquisition_channel"},{"device","device"},{"patch","CASE WHEN register_date<DATE '2026-03-02' THEN 'pre_patch1' WHEN register_date<DATE '2026-05-01' THEN 'post_patch1' ELSE 'post_patch2' END"}}]," UNION ALL "]<>" ORDER BY dimension,category,d"];
 groups=Map[Function[r,ci=HWilson[r["retained"],r["eligible"]];Join[r,<|"ci_low"->ci[[1]],"ci_high"->ci[[2]]|>]],groups];HCSV[HPath["outputs","tables","retention_breakdown.csv"],groups];
 Do[$HM["retention/"<>r["dimension"]<>"/"<>r["category"]<>"/d"<>ToString[r["d"]]]=r["rate"];$HM["population/"<>r["dimension"]<>"/"<>r["category"]<>"/d"<>ToString[r["d"]]]=r["eligible"],{r,groups}];
 weekly=HQuery[q<>"SELECT floor((register_date-DATE '2026-01-01')/7.0)::int week,d,count(*) eligible,avg(retained)::float8 rate FROM x GROUP BY week,d ORDER BY week,d"];HCSV[HPath["outputs","tables","weekly_retention.csv"],weekly];curve];
